name: inventory-service
services:
  db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inv
      POSTGRES_PASSWORD: inv
    restart: unless-stopped
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inv -d inventory"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PACKAGES_USER: ${GITHUB_PACKAGES_USER}
        GITHUB_PACKAGES_TOKEN: ${GITHUB_PACKAGES_TOKEN}
      secrets:
        - maven_settings
    image: inventory-service:local
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory
      SPRING_DATASOURCE_USERNAME: inv
      SPRING_DATASOURCE_PASSWORD: inv
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
volumes:
  pgdata:

networks:
  default:
    name: inventory-net

secrets:
  maven_settings:
    file: ./.mvn/settings.xml
